x-variables: &variables
  ENV_STAGE: local

services:
  web:
    hostname: web-blog
    build:
      context: . 
      # указывает стартовую точку, просто точка == директория где лежит сам docker-compose
      # стартовую точка актуальна для команд внутри dockerfile
      # для  COPY ./web/src/requirements  ./src/requirements источником будет => папка_где_docker-compose.yml/web/src/requirements
      dockerfile: docker/dev/web/Dockerfile # указывает дальнейший путь => папка_где_docker-compose.yml/docker/dev/web/Dockerfile
    volumes:
      - ./web/:/usr/src/web/ #  => папка_где_docker-compose.yml/web/:абсолютный путь к volume
      # дает возможность отображать изменения в коде без пересборки контейнера(только для режима отладки, на проде использовать COPY)
      - postgres_socket:/postgres_socket
    ports:
      - "8008:8000"
    environment:
      <<: *variables
    env_file:
        # путь интерпретируется относительно местоположения самого файла docker-compose.yml
        # ./docker/dev/env/.env == docker/dev/env/.env
      - docker/dev/env/.env #  => папка_где_docker-compose.yml/docker/dev/env/.env
      - docker/dev/env/.db.env
      - docker/dev/env/.mailhog.env
      - docker/prod/env/.data.env
    depends_on: [db, redis]
    restart: unless-stopped # при перегрузке сервера контейнер имеет то же состояние что и до
    networks:
      - microservice_network
      - separated_network
    extra_hosts:
      - "gateway-host:172.17.0.1"  # Linux OS get access from docker container to localhost
      # host.docker.internal - For docker in Windows and macOS. No other action is required.
      # If You need to connect to Postgresql in localhost, just use host.docker.internal instead of localhost
    healthcheck:
      test: curl --fail -s http://localhost:8000$$HEALTH_CHECK_URL || exit 1
      interval: 1m30s
      timeout: 3s
      retries: 3
  db:
    image: postgres:15.1-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - postgres_socket:/var/run/postgresql/
    env_file:
      - docker/dev/env/.db.env
    networks:
      - separated_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 50s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.0.8-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - separated_network
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 1m20s
      timeout: 5s
      retries: 3
  celery:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    entrypoint: ""
    command: celery -A src worker --beat -l info
    volumes:
      - ./web/:/usr/src/web/
      - postgres_socket:/postgres_socket
    environment:
      <<: *variables
    env_file:
      - docker/dev/env/.env
      - docker/dev/env/.db.env
      - docker/dev/env/.mailhog.env
      - docker/prod/env/.data.env
    depends_on: [redis]
    restart: unless-stopped
    networks:
      - separated_network
    extra_hosts:
      - "gateway-host:172.17.0.1"

volumes:
  postgres_data:
  postgres_socket:
  redis_data:

networks:
  microservice_network:
    driver: bridge
    name: local_microservice_network
  separated_network:
    driver: bridge
