services:
  nginx:
    image: staticfloat/nginx-certbot
    network_mode: host
    restart: 'always'
    container_name: nginx
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./docker/prod/nginx/certbot.conf:/etc/nginx/user.conf.d/nginx_template.conf:ro
      - ./docker/prod/nginx/conf.d/proxy.conf:/etc/nginx/user.conf.d/proxy.conf:ro
    environment:
      CERTBOT_EMAIL: 021alykar1990@gmail.com
      # variable names are space-separated
      ENVSUBST_VARS: APP
      APP: dev.kimaykin-django.ru
      APP_CHAT: chat.dev.kimaykin-django.ru


volumes:
  letsencrypt:
