# Generated by Django 4.2.6 on 2023-11-17 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_set_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Not_known'), (1, 'Male'), (2, 'Female'), (9, 'Not_applicable')], default=0
            ),
        ),
    ]
