# Generated by Django 4.2.6 on 2023-12-12 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0002_following_following_unique_following_and_more'),
        ('main', '0005_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(
                related_name='followers', through='actions.Following', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
