# Generated by Django 4.2.10 on 2024-05-22 07:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_user_following'),
    ]

    operations = []
