# Generated by Django 4.2.6 on 2023-10-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_tag_tagarticle_article_tags_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tagarticle',
            name='unique_tag_in_recipe',
        ),
        migrations.AddConstraint(
            model_name='tagarticle',
            constraint=models.UniqueConstraint(fields=('article', 'tag'), name='unique_tag_in_article'),
        ),
    ]
