# Generated by Django 4.2.6 on 2023-10-24 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_remove_tagarticle_unique_tag_in_recipe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagarticle',
            options={'ordering': ('-id',), 'verbose_name': 'article tag', 'verbose_name_plural': 'article tags'},
        ),
    ]
