# Generated by Django 4.2.6 on 2023-11-13 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0006_alter_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
    ]
