# Generated by Django 4.2.6 on 2024-02-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0007_actionusers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='actionusers',
            constraint=models.UniqueConstraint(fields=('user', 'action'), name='unique_familiarization'),
        ),
    ]
