# Generated by Django 4.2.6 on 2024-02-17 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0008_actionusers_unique_familiarization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionusers',
            options={'verbose_name_plural': 'Action Users'},
        ),
    ]
