# Generated by Django 4.2.6 on 2024-02-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0009_alter_actionusers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
