# скопировано, не закончено
name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
    deploy:
        name: Deploy to Server
        runs-on: ubuntu-latest
        # needs: build_and_push

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Add SSH key
          uses: webfactory/ssh-agent@v0.8.0
          with:
            ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
            ssh-passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}

        - name: Copy Docker Compose file to server
          uses: appleboy/scp-action@v0.0.4
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            source: 'docker-compose.yml'
            target: '/path/to/remote/docker-compose.yml'

        - name: Copy .env folder to server
          uses: appleboy/scp-action@v0.0.4
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            source: '.env_folder/*'
            target: '/path/to/remote/.env_folder/'
